In [13]:
import os
import numpy as np
import pandas as pd
import mne
import neurokit2 as nk
from scipy.signal import resample
from scipy.signal import welch
import matplotlib.pyplot as plt
import ast

# Ictal ecg

In [14]:
import pandas as pd

ictal= pd.read_xml("F:\graduation project\data\Code\ictal37.xml")

ictal['signal'] = ictal['signal'].apply(ast.literal_eval)
ictal['signal'] = ictal['signal'].apply(np.array)

ictal['times'] = ictal['times'].apply(ast.literal_eval)
ictal['times'] = ictal['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\4048785267.py:3: SyntaxWarning: invalid escape sequence '\g'
  ictal= pd.read_xml("F:\graduation project\data\Code\ictal37.xml")

In [15]:
ictal.head()
labels_counts = ictal['label'].value_counts()
print(labels_counts)

label
ictal    27
Name: count, dtype: int64

In [16]:
print(ictal['signal'].iloc[0])

[0.52767439 0.5289761  0.52981286 ... 0.56541132 0.56511654 0.56453865]

In [17]:
len(ictal['signal'].iloc[0])

15360

# ictal acc

In [18]:
import pandas as pd

ictalacc= pd.read_xml("F:\graduation project\data\Code\ictalacc37.xml")

ictalacc['signal'] = ictalacc['signal'].apply(ast.literal_eval)
ictalacc['signal'] = ictalacc['signal'].apply(np.array)

ictalacc['times'] = ictalacc['times'].apply(ast.literal_eval)
ictalacc['times'] = ictalacc['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\2873350333.py:3: SyntaxWarning: invalid escape sequence '\g'
  ictalacc= pd.read_xml("F:\graduation project\data\Code\ictalacc37.xml")

In [19]:
ictalacc.head()
labels_counts = ictalacc['label'].value_counts()
print(labels_counts)

label
ictal    27
Name: count, dtype: int64

In [20]:
print(ictalacc['signal'].iloc[0])

[[0.47760822 0.47950966 0.47789301 ... 0.47556226 0.47526229 0.47600786]
 [0.49497159 0.4936763  0.49127832 ... 0.49239811 0.49123225 0.49154515]
 [0.51674548 0.51674548 0.51674548 ... 0.51674548 0.51674548 0.51674548]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [21]:
len(ictalacc['signal'].iloc[0])

6

# normal ecg

In [22]:
import pandas as pd

normal = pd.read_xml("F:\graduation project\data\Code\Rnormal37.xml")

normal['signal'] = normal['signal'].apply(ast.literal_eval)
normal['signal'] = normal['signal'].apply(np.array)

normal['times'] = normal['times'].apply(ast.literal_eval)
normal['times'] = normal['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\3306257460.py:3: SyntaxWarning: invalid escape sequence '\g'
  normal = pd.read_xml("F:\graduation project\data\Code\Rnormal37.xml")

In [23]:
normal.head()
labels_counts = normal['label'].value_counts()
print(labels_counts)

label
normal    48
Name: count, dtype: int64

In [24]:
print(normal['signal'].iloc[0])

[0.53453674 0.50547051 0.48438811 ... 0.52961411 0.53295384 0.53868622]

In [25]:
len(normal['signal'].iloc[0])

15360

# normal ACC

In [26]:
import pandas as pd

normalacc = pd.read_xml("F:\graduation project\data\Code\Rnormalacc37.xml")

normalacc['signal'] = normalacc['signal'].apply(ast.literal_eval)
normalacc['signal'] = normalacc['signal'].apply(np.array)

normalacc['times'] = normalacc['times'].apply(ast.literal_eval)
normalacc['times'] = normalacc['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\3369581689.py:3: SyntaxWarning: invalid escape sequence '\g'
  normalacc = pd.read_xml("F:\graduation project\data\Code\Rnormalacc37.xml")

In [27]:
normalacc.head()
labels_counts = normalacc['label'].value_counts()
print(labels_counts)

label
normal    48
Name: count, dtype: int64

In [28]:
print(normalacc['signal'].iloc[0])

[[0.47997361 0.47014443 0.46846621 ... 0.47971193 0.47875353 0.47953252]
 [0.49869387 0.50459238 0.50669062 ... 0.49591696 0.49249843 0.49140896]
 [0.51674548 0.51674548 0.51674548 ... 0.51674548 0.51674548 0.51674548]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [29]:
len(normalacc['signal'].iloc[0])

6

# Preactial

In [30]:
import pandas as pd

pre= pd.read_xml("F:\graduation project\data\Code\preictal37.xml")

pre['signal'] = pre['signal'].apply(ast.literal_eval)
pre['signal'] = pre['signal'].apply(np.array)

pre['times'] = pre['times'].apply(ast.literal_eval)
pre['times'] = pre['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\785820818.py:3: SyntaxWarning: invalid escape sequence '\g'
  pre= pd.read_xml("F:\graduation project\data\Code\preictal37.xml")

In [31]:
pre.head()
labels_counts = pre['label'].value_counts()
print(labels_counts)

label
preictal    26
Name: count, dtype: int64

In [32]:
print(pre['signal'].iloc[0])

[0.54163382 0.54320646 0.54492359 ... 0.52832519 0.52792146 0.52755138]

In [33]:
len(pre['signal'].iloc[0])

15360

# Preactial acc

In [34]:
import pandas as pd

preictalacc= pd.read_xml("F:\graduation project\data\Code\preictalacc37.xml")

preictalacc['signal'] = preictalacc['signal'].apply(ast.literal_eval)
preictalacc['signal'] = preictalacc['signal'].apply(np.array)

preictalacc['times'] = preictalacc['times'].apply(ast.literal_eval)
preictalacc['times'] = preictalacc['times'].apply(np.array)

<>:3: SyntaxWarning: invalid escape sequence '\g'
<>:3: SyntaxWarning: invalid escape sequence '\g'
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\1591546115.py:3: SyntaxWarning: invalid escape sequence '\g'
  preictalacc= pd.read_xml("F:\graduation project\data\Code\preictalacc37.xml")

In [35]:
preictalacc.head()
labels_counts = preictalacc['label'].value_counts()
print(labels_counts)

label
preictal    26
Name: count, dtype: int64

In [36]:
print(preictalacc['signal'].iloc[0])

[[0.4762556  0.47894465 0.47725868 ... 0.47993994 0.48013708 0.47479569]
 [0.49678779 0.49671045 0.49324293 ... 0.49541594 0.49583638 0.49531649]
 [0.51674548 0.51674548 0.51674548 ... 0.51674548 0.51674548 0.51674548]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

In [37]:
len(preictalacc['signal'].iloc[0])

6

# Feature Extraction ECG

#### Detect R_Peaks & RR_Interval & HR_Series

In [38]:
def Detect_R_peaks(signal, times, show_plot=False):
    try:
        signal = np.array(signal, dtype=float)
        times = np.array(times, dtype=float)

        if len(signal) < 2 or len(times) < 2:
            return np.array([]), np.zeros(len(signal)), np.array([]), "window too short"
        if np.any(np.isnan(signal)) or np.any(np.isnan(times)):
            return np.array([]), np.zeros(len(signal)), np.array([]), "NaN detected"

        sfreq = 1 / np.mean(np.diff(times))
        clean_signal = nk.ecg_clean(signal, sampling_rate=sfreq, method="neurokit")
        signals, info = nk.ecg_process(clean_signal, sampling_rate=sfreq)
        R_peaks_idx = info["ECG_R_Peaks"]

        if len(R_peaks_idx) < 2:
            return np.array([]), np.zeros(len(signal)), np.array([]), "less than 2 R-peaks"

        R_peaks_times = times[R_peaks_idx]
        RR_intervals_s = np.diff(R_peaks_times)  # seconds

        # Convert RR_intervals to ms for HRV calculation
        RR_intervals_ms = RR_intervals_s * 1000.0

        HR_series_peaks = 60 / RR_intervals_s  # bpm
        HR_series = np.interp(times[1:], R_peaks_times[1:], HR_series_peaks)
        HR_series = np.insert(HR_series, 0, HR_series[0])

        if show_plot:
            nk.events_plot(R_peaks_idx, signal)

        return R_peaks_times, HR_series, RR_intervals_ms, "success"

    except Exception as e:
        return np.array([]), np.zeros(len(signal)), np.array([]), f"error: {e}"

In [39]:
def Apply_R_peak_Detection(df, show_plot=False):
    results = []
    for i, row in df.iterrows():
        print(f"Processing subject {row['subject']} | run {row['run']} | window {i}")
        signal = row['signal']
        times = row['times']

        R_peaks, HR_series, RR_intervals_ms, status = Detect_R_peaks(signal, times, show_plot=show_plot)

        results.append({
            'subject': row['subject'],
            'run': row['run'],
            'sex': row['sex'],
            'start_time': row['start_time'],
            'end_time': row['end_time'],
            'eventtype': row['eventType'],
            'label': row['label'],
            'signal': signal,
            'times': times,
            'R_peaks': R_peaks if status=="success" else np.array([]),
            'RR_intervals_ms': RR_intervals_ms if status=="success" else np.array([]),
            'HR_series': HR_series if status=="success" else np.zeros(len(signal)),
            'status': status
        })

    df_result = pd.DataFrame(results)
    print(f"Finished R-peak detection for {len(df_result)} windows.")
    return df_result

#### Feature Time Domain General

In [40]:
def Compute_HR_summary(df_hr):
    summary_list = []
    for idx, row in df_hr.iterrows():
        hr_series = np.array(row.get('HR_series', np.zeros_like(row['signal'])))
        if len(hr_series) > 0:
            summary = {
                'meanHR': np.mean(hr_series),
                'stdHR': np.std(hr_series),
                'minHR': np.min(hr_series),
                'maxHR': np.max(hr_series)
            }
        else:
            summary = {'meanHR': np.nan, 'stdHR': np.nan, 'minHR': np.nan, 'maxHR': np.nan}
        summary_list.append(summary)

    df_summary = pd.DataFrame(summary_list)
    df_hr_summary = pd.concat([df_hr.reset_index(drop=True), df_summary], axis=1)
    print(f"HR summary computed for {len(df_hr_summary)} windows.")
    return df_hr_summary

In [41]:
def Compute_Baseline_HR(df_hr, pre_ictal_only=False):
    baseline_dict = {}
    subjects = df_hr['subject'].unique()
    for subj in subjects:
        subj_data = df_hr[df_hr['subject'] == subj]
        if pre_ictal_only:
            subj_clean = subj_data[subj_data['label'] == 'normal']
        else:
            subj_clean = subj_data[~subj_data['label'].isin(['ictal', 'pre-ictal', 'post-ictal'])]
        subj_clean = subj_clean.head(int(600 / 60))  
        baseline_HR = np.nanmean(subj_clean['meanHR'])
        baseline_dict[subj] = baseline_HR
    return baseline_dict

In [42]:
def Compute_Delta_HR(df_hr, baseline_dict):
    delta_list = []
    for _, row in df_hr.iterrows():
        subj = row['subject']
        base = baseline_dict.get(subj, np.nan)
        delta = row['meanHR'] - base if not np.isnan(base) else np.nan
        delta_list.append(delta)
    df_hr['Delta_HR'] = delta_list
    print("ΔHR computed and added to DataFrame.")
    return df_hr

#### Feature HRV

In [43]:
def Compute_HRV(df_rpeaks):
    hrv_list = []
    for idx, row in df_rpeaks.iterrows():
        RR_intervals_ms = row.get('RR_intervals_ms', np.array([]))
        if len(RR_intervals_ms) > 1:
            meanRR = np.mean(RR_intervals_ms)
            SDNN   = np.std(RR_intervals_ms, ddof=1)
            RMSSD  = np.sqrt(np.mean(np.diff(RR_intervals_ms)**2))
            pNN50  = np.sum(np.diff(RR_intervals_ms) > 50.0) / len(RR_intervals_ms) * 100
            meanHRV = 60000.0 / meanRR  # bpm
            HRV_features = {
                'meanRR_ms': meanRR,
                'SDNN_ms': SDNN,
                'RMSSD_ms': RMSSD,
                'pNN50': pNN50,
                'meanHRV_bpm': meanHRV
            }
        else:
            HRV_features = {
                'meanRR_ms': np.nan,
                'SDNN_ms': np.nan,
                'RMSSD_ms': np.nan,
                'pNN50': np.nan,
                'meanHRV_bpm': np.nan
            }
        hrv_list.append(HRV_features)

    df_hrv_features = pd.DataFrame(hrv_list)
    df_hrv = pd.concat([df_rpeaks.reset_index(drop=True), df_hrv_features], axis=1)
    print(f"HRV features computed for {len(df_hrv)} windows using ms standard.")
    return df_hrv

In [44]:
def Add_Missing_ECG_Features(df):
    extra_feats = []
    for idx, row in df.iterrows():
        signal = np.array(row['signal'], dtype=float)
        R_peaks = np.array(row['R_peaks'], dtype=int)
        
        mean_ecg = float(np.mean(signal)) if 'mean_ecg' not in row else row['mean_ecg']
        std_ecg  = float(np.std(signal)) if 'std_ecg' not in row else row['std_ecg']
        rms_ecg  = float(np.sqrt(np.mean(signal**2))) if 'rms_ecg' not in row else row['rms_ecg']
        ptp_ecg  = float(np.ptp(signal)) if 'ptp_ecg' not in row else row['ptp_ecg']
        
        fs = 1 / np.mean(np.diff(row['times'])) if len(row['times']) > 1 else 1.0
        freqs, psd = welch(signal, fs=fs, nperseg=min(1024, len(signal)))
        total_power = float(np.sum(psd)) if 'total_power_ecg' not in row else row['total_power_ecg']
        band_idx = (freqs >= 0.5) & (freqs <= 3)
        bp_0_5_3 = float(np.trapz(psd[band_idx], freqs[band_idx])) if np.any(band_idx) and 'bp_0_5_3_ecg' not in row else row.get('bp_0_5_3_ecg', 0.0)
        
        n_beats = len(R_peaks) if 'n_beats' not in row else row['n_beats']
        
        extra_feats.append({
            'mean_ecg': mean_ecg,
            'std_ecg': std_ecg,
            'rms_ecg': rms_ecg,
            'ptp_ecg': ptp_ecg,
            'total_power_ecg': total_power,
            'bp_0_5_3_ecg': bp_0_5_3,
            'n_beats': n_beats
        })
    
    df_extra = pd.DataFrame(extra_feats)
    df_combined = pd.concat([df.reset_index(drop=True), df_extra], axis=1)
    print(f"Added missing ECG features for {len(df_combined)} windows.")
    return df_combined

#### Apply

In [45]:
def Features(df_cleaned, pre_ictal_only_baseline=False, show_rpeaks=False):
    
    print("\nDetecting R-peaks and computing HR series...")
    df_rpeaks = Apply_R_peak_Detection(df_cleaned, show_plot=show_rpeaks)
    
    print("\nComputing HR summary features...")
    df_hr = Compute_HR_summary(df_rpeaks)
    
    print("\nComputing baseline HR & ΔHR...")
    baseline_dict = Compute_Baseline_HR(df_hr, pre_ictal_only=pre_ictal_only_baseline)
    df_delta_hr = Compute_Delta_HR(df_hr, baseline_dict)
    
    print("\nComputing HRV features (all in ms)...")
    df_hrv = Compute_HRV(df_delta_hr)
    
    print("\nAdding ECG amplitude & frequency features...")
    df_final = Add_Missing_ECG_Features(df_hrv)
    
    print("\nProcessing complete.")
    print("Summary of labels:")
    print(df_final['label'].value_counts())
    
    return {
        "df_rpeaks": df_rpeaks,
        "df_hr": df_hr,
        "baseline_dict": baseline_dict,
        "df_delta_hr": df_delta_hr,
        "df_hrv": df_final
    }

## feature

### ictal

In [46]:
ictal=Apply_R_peak_Detection(df=ictal, show_plot=False)

Processing subject 125 | run 37 | window 0
Processing subject 125 | run 37 | window 1
Processing subject 125 | run 37 | window 2
Processing subject 125 | run 37 | window 3
Processing subject 125 | run 37 | window 4
Processing subject 125 | run 37 | window 5
Processing subject 125 | run 37 | window 6
Processing subject 125 | run 37 | window 7
Processing subject 125 | run 37 | window 8
Processing subject 125 | run 37 | window 9
Processing subject 125 | run 37 | window 10
Processing subject 125 | run 37 | window 11
Processing subject 125 | run 37 | window 12
Processing subject 125 | run 37 | window 13
Processing subject 125 | run 37 | window 14
Processing subject 125 | run 37 | window 15
Processing subject 125 | run 37 | window 16
Processing subject 125 | run 37 | window 17
Processing subject 125 | run 37 | window 18
Processing subject 125 | run 37 | window 19
Processing subject 125 | run 37 | window 20
Processing subject 125 | run 37 | window 21
Processing subject 125 | run 37 | window 22
Processing subject 125 | run 37 | window 23
Processing subject 125 | run 37 | window 24
Processing subject 125 | run 37 | window 25
Processing subject 125 | run 37 | window 26
Finished R-peak detection for 27 windows.

In [47]:
ictal=Compute_HR_summary(ictal)
dicts=Compute_Baseline_HR(ictal, pre_ictal_only=True)
ictal=Compute_Delta_HR(ictal, dicts)  
ictal=Compute_HRV(ictal)
ictal=Add_Missing_ECG_Features(ictal)

HR summary computed for 27 windows.
ΔHR computed and added to DataFrame.
HRV features computed for 27 windows using ms standard.
Added missing ECG features for 27 windows.

C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\452005005.py:11: RuntimeWarning: Mean of empty slice
  baseline_HR = np.nanmean(subj_clean['meanHR'])
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\122617723.py:16: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  bp_0_5_3 = float(np.trapz(psd[band_idx], freqs[band_idx])) if np.any(band_idx) and 'bp_0_5_3_ecg' not in row else row.get('bp_0_5_3_ecg', 0.0)

In [48]:
ictal.columns

Index(['subject', 'run', 'sex', 'start_time', 'end_time', 'eventtype', 'label',
       'signal', 'times', 'R_peaks', 'RR_intervals_ms', 'HR_series', 'status',
       'meanHR', 'stdHR', 'minHR', 'maxHR', 'Delta_HR', 'meanRR_ms', 'SDNN_ms',
       'RMSSD_ms', 'pNN50', 'meanHRV_bpm', 'mean_ecg', 'std_ecg', 'rms_ecg',
       'ptp_ecg', 'total_power_ecg', 'bp_0_5_3_ecg', 'n_beats'],
      dtype='object')

### preictal

In [49]:
preictal=Apply_R_peak_Detection(df=pre, show_plot=False)

Processing subject 125 | run 37 | window 0
Processing subject 125 | run 37 | window 1
Processing subject 125 | run 37 | window 2
Processing subject 125 | run 37 | window 3
Processing subject 125 | run 37 | window 4
Processing subject 125 | run 37 | window 5
Processing subject 125 | run 37 | window 6
Processing subject 125 | run 37 | window 7
Processing subject 125 | run 37 | window 8
Processing subject 125 | run 37 | window 9
Processing subject 125 | run 37 | window 10
Processing subject 125 | run 37 | window 11
Processing subject 125 | run 37 | window 12
Processing subject 125 | run 37 | window 13
Processing subject 125 | run 37 | window 14
Processing subject 125 | run 37 | window 15
Processing subject 125 | run 37 | window 16
Processing subject 125 | run 37 | window 17
Processing subject 125 | run 37 | window 18
Processing subject 125 | run 37 | window 19
Processing subject 125 | run 37 | window 20
Processing subject 125 | run 37 | window 21
Processing subject 125 | run 37 | window 22
Processing subject 125 | run 37 | window 23
Processing subject 125 | run 37 | window 24
Processing subject 125 | run 37 | window 25
Finished R-peak detection for 26 windows.

In [50]:
preictal=Compute_HR_summary(preictal)
dicts=Compute_Baseline_HR(preictal, pre_ictal_only=True)
preictal=Compute_Delta_HR(preictal, dicts)  
preictal=Compute_HRV(preictal)
preictal=Add_Missing_ECG_Features(preictal)

HR summary computed for 26 windows.
ΔHR computed and added to DataFrame.
HRV features computed for 26 windows using ms standard.
Added missing ECG features for 26 windows.

C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\452005005.py:11: RuntimeWarning: Mean of empty slice
  baseline_HR = np.nanmean(subj_clean['meanHR'])
C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\122617723.py:16: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  bp_0_5_3 = float(np.trapz(psd[band_idx], freqs[band_idx])) if np.any(band_idx) and 'bp_0_5_3_ecg' not in row else row.get('bp_0_5_3_ecg', 0.0)

In [51]:
preictal.columns

Index(['subject', 'run', 'sex', 'start_time', 'end_time', 'eventtype', 'label',
       'signal', 'times', 'R_peaks', 'RR_intervals_ms', 'HR_series', 'status',
       'meanHR', 'stdHR', 'minHR', 'maxHR', 'Delta_HR', 'meanRR_ms', 'SDNN_ms',
       'RMSSD_ms', 'pNN50', 'meanHRV_bpm', 'mean_ecg', 'std_ecg', 'rms_ecg',
       'ptp_ecg', 'total_power_ecg', 'bp_0_5_3_ecg', 'n_beats'],
      dtype='object')

### normal

In [52]:
normal=Apply_R_peak_Detection(df=normal, show_plot=False)

Processing subject 125 | run 37 | window 0
Processing subject 125 | run 37 | window 1
Processing subject 125 | run 37 | window 2
Processing subject 125 | run 37 | window 3
Processing subject 125 | run 37 | window 4
Processing subject 125 | run 37 | window 5
Processing subject 125 | run 37 | window 6
Processing subject 125 | run 37 | window 7
Processing subject 125 | run 37 | window 8
Processing subject 125 | run 37 | window 9
Processing subject 125 | run 37 | window 10
Processing subject 125 | run 37 | window 11
Processing subject 125 | run 37 | window 12
Processing subject 125 | run 37 | window 13
Processing subject 125 | run 37 | window 14
Processing subject 125 | run 37 | window 15
Processing subject 125 | run 37 | window 16
Processing subject 125 | run 37 | window 17
Processing subject 125 | run 37 | window 18
Processing subject 125 | run 37 | window 19
Processing subject 125 | run 37 | window 20
Processing subject 125 | run 37 | window 21
Processing subject 125 | run 37 | window 22
Processing subject 125 | run 37 | window 23
Processing subject 125 | run 37 | window 24
Processing subject 125 | run 37 | window 25
Processing subject 125 | run 37 | window 26
Processing subject 125 | run 37 | window 27
Processing subject 125 | run 37 | window 28
Processing subject 125 | run 37 | window 29
Processing subject 125 | run 37 | window 30
Processing subject 125 | run 37 | window 31
Processing subject 125 | run 37 | window 32
Processing subject 125 | run 37 | window 33
Processing subject 125 | run 37 | window 34
Processing subject 125 | run 37 | window 35
Processing subject 125 | run 37 | window 36
Processing subject 125 | run 37 | window 37
Processing subject 125 | run 37 | window 38
Processing subject 125 | run 37 | window 39
Processing subject 125 | run 37 | window 40
Processing subject 125 | run 37 | window 41
Processing subject 125 | run 37 | window 42
Processing subject 125 | run 37 | window 43
Processing subject 125 | run 37 | window 44
Processing subject 125 | run 37 | window 45
Processing subject 125 | run 37 | window 46
Processing subject 125 | run 37 | window 47
Finished R-peak detection for 48 windows.

In [53]:
normal=Compute_HR_summary(normal)
dicts=Compute_Baseline_HR(normal, pre_ictal_only=True)
normal=Compute_Delta_HR(normal, dicts)  
normal=Compute_HRV(normal)
normal=Add_Missing_ECG_Features(normal)

HR summary computed for 48 windows.
ΔHR computed and added to DataFrame.
HRV features computed for 48 windows using ms standard.
Added missing ECG features for 48 windows.

C:\Users\Abdelrhamn\AppData\Local\Temp\ipykernel_3544\122617723.py:16: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  bp_0_5_3 = float(np.trapz(psd[band_idx], freqs[band_idx])) if np.any(band_idx) and 'bp_0_5_3_ecg' not in row else row.get('bp_0_5_3_ecg', 0.0)

In [54]:
normal.columns

Index(['subject', 'run', 'sex', 'start_time', 'end_time', 'eventtype', 'label',
       'signal', 'times', 'R_peaks', 'RR_intervals_ms', 'HR_series', 'status',
       'meanHR', 'stdHR', 'minHR', 'maxHR', 'Delta_HR', 'meanRR_ms', 'SDNN_ms',
       'RMSSD_ms', 'pNN50', 'meanHRV_bpm', 'mean_ecg', 'std_ecg', 'rms_ecg',
       'ptp_ecg', 'total_power_ecg', 'bp_0_5_3_ecg', 'n_beats'],
      dtype='object')

# Features ACC

In [55]:
def extract_acc_features(seg_df):

    df = seg_df.copy()

    df["acc_magnitude"] = 0.0
    df["activity_score"] = 0.0
    df["rms_mag"] = 0.0
    df["std_mag"] = 0.0

    for idx, row in df.iterrows():

        # convert string → list
        acc_x = np.array(ast.literal_eval(row["ACC_X"]), dtype=float)
        acc_y = np.array(ast.literal_eval(row["ACC_Y"]), dtype=float)
        acc_z = np.array(ast.literal_eval(row["ACC_Z"]), dtype=float)

        magnitude = np.sqrt(acc_x**2 + acc_y**2 + acc_z**2)

        df.at[idx, "acc_magnitude"] = np.mean(magnitude)
        df.at[idx, "activity_score"] = np.mean(np.abs(np.diff(magnitude)))
        df.at[idx, "rms_mag"] = np.sqrt(np.mean(magnitude**2))
        df.at[idx, "std_mag"] = np.std(magnitude)

    return df

In [56]:
def calculate_acc_score(acc_df):
    cols = ["acc_magnitude", "activity_score", "rms_mag", "std_mag"]

    # Convert columns to numeric
    for c in cols:
        acc_df[c] = pd.to_numeric(acc_df[c], errors="coerce")

    # Replace NaN with 0
    acc_df[cols] = acc_df[cols].fillna(0)

    # Calculate average score
    acc_df["acc_score"] = (
        acc_df["acc_magnitude"] +
        acc_df["activity_score"] +
        acc_df["rms_mag"] +
        acc_df["std_mag"]
    ) / 4

    # Normalize (Min-Max)
    acc_df["acc_score"] = (
        acc_df["acc_score"] - acc_df["acc_score"].min()
    ) / (
        acc_df["acc_score"].max()
        - acc_df["acc_score"].min()
        + 1e-8
    )

    return acc_df

In [57]:
ictalacc=extract_acc_features(ictalacc)
normalacc=extract_acc_features(normalacc)
preictalacc=extract_acc_features(preictalacc)

In [58]:
ictalacc=calculate_acc_score(ictalacc)
normalacc=calculate_acc_score(normalacc)
preictalacc=calculate_acc_score(preictalacc)

In [59]:
normalacc.columns

Index(['window_id', 'subject', 'run', 'start_time', 'end_time', 'signal',
       'ACC_X', 'ACC_Y', 'ACC_Z', 'acc_magnitude', 'times', 'label',
       'preictal_ratio', 'ictal_ratio', 'postictal_ratio', 'window_length',
       'sfreq', 'sex', 'activity_score', 'rms_mag', 'std_mag', 'acc_score'],
      dtype='object')

In [60]:
preictalacc.columns

Index(['window_id', 'subject', 'run', 'start_time', 'end_time', 'signal',
       'ACC_X', 'ACC_Y', 'ACC_Z', 'acc_magnitude', 'times', 'label',
       'preictal_ratio', 'ictal_ratio', 'postictal_ratio', 'window_length',
       'sfreq', 'sex', 'activity_score', 'rms_mag', 'std_mag', 'acc_score'],
      dtype='object')

In [61]:
ictalacc.columns

Index(['window_id', 'subject', 'run', 'start_time', 'end_time', 'signal',
       'ACC_X', 'ACC_Y', 'ACC_Z', 'acc_magnitude', 'times', 'label',
       'preictal_ratio', 'ictal_ratio', 'postictal_ratio', 'window_length',
       'sfreq', 'sex', 'activity_score', 'rms_mag', 'std_mag', 'acc_score'],
      dtype='object')

# Model ECG

In [62]:
import joblib
model_path = r"F:\graduation project\data\Code\final\ecg 60s 10min\patient_models100_csv\patient_125.0_model.pkl"
model = joblib.load(model_path)

In [63]:
feature_cols = [
    'meanHR','stdHR','minHR','maxHR','meanRR_ms','SDNN_ms','RMSSD_ms',
    'pNN50','meanHRV_bpm','mean_ecg','std_ecg','rms_ecg','ptp_ecg',
    'total_power_ecg','bp_0_5_3_ecg','n_beats'
]

In [64]:
def predict_probabilities(features_values):

    if isinstance(features_values, dict):
        X = pd.DataFrame([features_values])

    elif isinstance(features_values, list):
        X = pd.DataFrame([features_values], columns=feature_cols)

    elif isinstance(features_values, pd.DataFrame):
        X = features_values

    else:
        raise ValueError("Input must be dict, list, or DataFrame")

    probs = model.predict_proba(X)

    for i, p in enumerate(probs):
        print(f"Sample {i}:")
        print(f"Class 0 probability: {p[0]:.4f}")
        print(f"Class 1 probability: {p[1]:.4f}")
        print(f"Class 2 probability: {p[2]:.4f}")
        print("-" * 30)

    return probs

In [65]:
X_inputI =ictal[feature_cols]
X_inputN =normal[feature_cols]
X_inputPR =preictal[feature_cols]

In [66]:
y_probaI = model.predict_proba(X_inputI)  
y_predI = model.predict(X_inputI)

y_probaN = model.predict_proba(X_inputN)  
y_predN = model.predict(X_inputN)

y_probaPR = model.predict_proba(X_inputPR)  
y_predPR = model.predict(X_inputPR)

In [67]:
ictal["pred_label"] = y_predI

ictal["p_class0"] = y_probaI[:, 0]
ictal["p_class1"] = y_probaI[:, 1]
ictal["p_class2"] = y_probaI[:, 2]

Label_counts =ictal['pred_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

   Label  Count
0      0     26
1      1      1

In [68]:
preictal["pred_label"] = y_predPR

preictal["p_class0"] = y_probaPR[:, 0]
preictal["p_class1"] = y_probaPR[:, 1]
preictal["p_class2"] = y_probaPR[:, 2]

Label_counts =preictal['pred_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

   Label  Count
0      2     26

In [69]:
normal["pred_label"] = y_predN

normal["p_class0"] = y_probaN[:, 0]
normal["p_class1"] = y_probaN[:, 1]
normal["p_class2"] = y_probaN[:, 2]

Label_counts =normal['pred_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

   Label  Count
0      1     41
1      2      7

# fusion

In [70]:
import numpy as np
import pandas as pd

def predict_fusion(ecg_df, acc_df, fusion_model):

    X_fusion = np.hstack([
        ecg_df[["p_class0", "p_class1", "p_class2"]].values,
        acc_df[["acc_score"]].values
    ])

    y_pred = fusion_model.predict(X_fusion)
    y_prob = fusion_model.predict_proba(X_fusion)

    result = pd.DataFrame({
        "predicted_label": y_pred,
        "prob_class0": y_prob[:, 0],
        "prob_class1": y_prob[:, 1],
        "prob_class2": y_prob[:, 2]
    })

    return result

In [71]:
fusion_path = r"F:\graduation project\data\fusion_patient_125.pkl"
fusion_model = joblib.load(fusion_path)

In [72]:
NORMAL=predict_fusion(normal, normalacc, fusion_model )
ICTAL =predict_fusion(ictal, ictalacc, fusion_model )
Preactal =predict_fusion(preictal, preictalacc, fusion_model )

In [73]:
ICTAL.head()

  predicted_label  prob_class0  prob_class1  prob_class2
0           ictal        0.940         0.06        0.000
1           ictal        0.905         0.09        0.005
2           ictal        0.785         0.18        0.035
3           ictal        1.000         0.00        0.000
4          normal        0.480         0.52        0.000

In [74]:
Preactal.head()

  predicted_label  prob_class0  prob_class1  prob_class2
0        preictal         0.01         0.28         0.71
1        preictal         0.00         0.00         1.00
2        preictal         0.00         0.00         1.00
3        preictal         0.00         0.00         1.00
4        preictal         0.00         0.00         1.00

In [75]:
NORMAL.head()

  predicted_label  prob_class0  prob_class1  prob_class2
0          normal         0.20         0.80          0.0
1          normal         0.04         0.96          0.0
2          normal         0.00         1.00          0.0
3          normal         0.00         1.00          0.0
4          normal         0.00         1.00          0.0

In [76]:
Label_counts =NORMAL['predicted_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

      Label  Count
0    normal     47
1  preictal      1

In [77]:
Label_counts =ICTAL['predicted_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

    Label  Count
0   ictal     26
1  normal      1

In [78]:
Label_counts =Preactal['predicted_label'].value_counts().reset_index()
Label_counts.columns = ['Label', 'Count']
Label_counts

      Label  Count
0  preictal     26